@startuml
participant "Camara:Camara" as Camara
participant "ctrl:ControladorPrincipal" as ControladorPrincipal
participant "Api:ApiBaseDeDatos" as ApiBaseDeDatos
participant "Api:ApiImpresora" as ApiImpresora 
participant "Deteccion:Deteccion" as Deteccion
participant "<<Multiobjetos>>Detecciones:Deteccion" as Detecciones 
participant "Api:ApiCorreo" as Correo 

'Cada cámara, detecta automáticamente al vehículo cuando pasa y envía a nuestro 
'sistema los siguientes datos: fecha y hora, id de la cámara, patente y velocidad.
Camara -> ControladorPrincipal: Detectar Vehiculo(Fecha, Hora, IdCamara, Patente, velocidad)
activate ControladorPrincipal

note right of ControladorPrincipal: DatosPaso = FechaCaptura, HoraCaptura,\n IdCamara, Patente, Velocidad 

create Deteccion
ControladorPrincipal -> Deteccion: create(datosPaso)

ControladorPrincipal -> Detecciones: add(deteccion)
activate Detecciones
Detecciones -> ControladorPrincipal: <<null>>
deactivate Detecciones

'si la velocidad es mayor a 70km/h
alt Velocidad > 70km/h 


'el sistema envía los datos a una API que se encargará de guardarlos en una base de datos
ControladorPrincipal -> ApiBaseDeDatos: Registrar en Base de datos (DatosPaso)
activate ApiBaseDeDatos

ApiBaseDeDatos -> ControladorPrincipal: <<null>>
deactivate ApiBaseDeDatos

ControladorPrincipal -> Correo: EnviarEmail(Deteccion, avisos@ciudad)
activate Correo
Correo -> ControladorPrincipal: <<null>>
deactivate Correo
'el sistema envía un correo con los datos que envió la cámara a la cuenta "avisos@ciudad"

   'si la velocidad es mayor a 100km/h
   alt Velocidad > 100km/h
  
   ControladorPrincipal -> ApiBaseDeDatos: Registrar en Base de datos (DatosPaso)
   activate ApiBaseDeDatos
   ApiBaseDeDatos -> ControladorPrincipal: <<null>>
   deactivate ApiBaseDeDatos
   
  
   ControladorPrincipal -> Correo: EnviarEmail(Deteccion, alertas@ciudad)
   activate Correo
   Correo -> ControladorPrincipal: <<null>>
   deactivate Correo  
   
   
       loop Repetir 3 veces
     
       ControladorPrincipal -> ApiImpresora: print(DatosPaso)
       activate ApiImpresora
       
       ApiImpresora -> ControladorPrincipal: <<null>>
       
       deactivate ApiImpresora
       
       end
    end   
    
    
    
end

ControladorPrincipal -> Camara: <<null>>

'DESACTÍVALO SOLO AL FINAL
deactivate ControladorPrincipal 

@enduml
